# Generated by Django 5.1.1 on 2024-10-13 10:01

import petstagram_2024.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_tagged_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images', validators=[petstagram_2024.photos.validators.FileSizeValidator(5)]),
        ),
    ]
